// CodeGenerator.swift — 可视化工作流 → Freqtrade Python 策略代码生成
// Phase 1: 基础指标节点 → populate_indicators 代码

import Foundation

// MARK: - CodeGenError

enum CodeGenError: LocalizedError {
    case validationFailed([String])
    case cycleDetected

    var errorDescription: String? {
        switch self {
        case .validationFailed(let issues):
            return "验证失败: \(issues.joined(separator: ", "))"
        case .cycleDetected:
            return "检测到循环依赖"
        }
    }
}

// MARK: - CodeGenerator

struct CodeTemplate {
    let indicatorCode: ((CanvasNode, [String: String]) -> String)?
    let entrySignalCode: ((CanvasNode, [String: String]) -> String)?
    let exitSignalCode: ((CanvasNode, [String: String]) -> String)?
}

struct CodeGenerator {

    // MARK: - Public API

    func generate(from graph: WorkflowGraph, strategyName: String) throws -> String {
        // 1. Validate
        let issues = validate(graph)
        guard issues.isEmpty else {
            throw CodeGenError.validationFailed(issues)
        }

        // 2. Topological sort
        let sorted = try topologicalSort(graph)

        // 3. Generate code
        let className = strategyName
            .replacingOccurrences(of: " ", with: "")
            .replacingOccurrences(of: "-", with: "")

        var code = """
        # Auto-generated by PulseDesk Canvas
        # Strategy: \(strategyName)
        # Generated: \(ISO8601DateFormatter().string(from: Date()))

        from freqtrade.strategy import IStrategy, merge_informative_pair
        from freqtrade.strategy import DecimalParameter, IntParameter
        import talib.abstract as ta
        from pandas import DataFrame
        import numpy as np


        class \(className)(IStrategy):
            \"\"\"
            \(strategyName) — generated by PulseDesk visual canvas.
            \"\"\"

            INTERFACE_VERSION = 3

        """

        // Separate nodes by phase
        let indicatorNodes = sorted.filter { $0.nodeType.hasPrefix("indicator.") || $0.nodeType.hasPrefix("transform.") || $0.nodeType.hasPrefix("filter.") }
        let entryNodes = sorted.filter { $0.nodeType == "strategy.entry" }
        let exitNodes = sorted.filter { $0.nodeType == "strategy.exit" }

        // populate_indicators
        code += "    def populate_indicators(self, dataframe: DataFrame, metadata: dict) -> DataFrame:\n"

        if indicatorNodes.isEmpty {
            code += "        pass\n"
        } else {
            for node in indicatorNodes {
                if let template = templateRegistry[node.nodeType], let indicatorFn = template.indicatorCode {
                    let inputVars = resolveInputVariables(node: node, graph: graph)
                    code += indicatorFn(node, inputVars)
                } else {
                    code += generateNodeCode(node, graph: graph)
                }
            }
        }

        code += "\n        return dataframe\n\n"

        // populate_entry_trend
        code += "    def populate_entry_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:\n"
        if entryNodes.isEmpty {
            code += "        pass\n"
        } else {
            for node in entryNodes {
                code += generateEntryCode(node, graph: graph)
            }
        }
        code += "\n        return dataframe\n\n"

        // populate_exit_trend
        code += "    def populate_exit_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:\n"
        if exitNodes.isEmpty {
            code += "        pass\n"
        } else {
            for node in exitNodes {
                code += generateExitCode(node, graph: graph)
            }
        }
        code += "\n        return dataframe\n"

        return code
    }

    // MARK: - Validation

    func validate(_ graph: WorkflowGraph) -> [String] {
        var issues: [String] = []

        // Check for orphan nodes (no edges at all, except data sources which have no inputs)
        for node in graph.nodes {
            let def = NodeRegistry.definition(for: node.nodeType)
            let hasInput = def?.inputPorts.isEmpty ?? true
            let hasEdge = graph.edges.contains { $0.sourceNodeId == node.id || $0.targetNodeId == node.id }
            if !hasInput && !hasEdge && !(node.nodeType.hasPrefix("data.")) {
                issues.append("孤立节点: \(def?.name ?? node.nodeType)")
            }
        }

        // Check required inputs are connected
        for node in graph.nodes {
            let def = NodeRegistry.definition(for: node.nodeType)
            guard let def else { continue }
            for port in def.inputPorts where port.isRequired {
                let connected = graph.edges.contains { $0.targetNodeId == node.id && $0.targetPortKey == port.key }
                if !connected {
                    issues.append("\(def.name) 缺少必需输入: \(port.name)")
                }
            }
        }

        return issues
    }

    // MARK: - Topological Sort (Kahn's algorithm)

    func topologicalSort(_ graph: WorkflowGraph) throws -> [CanvasNode] {
        var inDegree: [UUID: Int] = [:]
        for node in graph.nodes { inDegree[node.id] = 0 }
        for edge in graph.edges { inDegree[edge.targetNodeId, default: 0] += 1 }

        var queue: [UUID] = graph.nodes.filter { inDegree[$0.id] == 0 }.map(\.id)
        var result: [CanvasNode] = []

        while !queue.isEmpty {
            let id = queue.removeFirst()
            guard let node = graph.nodes.first(where: { $0.id == id }) else { continue }
            result.append(node)
            for edge in graph.edges where edge.sourceNodeId == id {
                inDegree[edge.targetNodeId, default: 0] -= 1
                if inDegree[edge.targetNodeId] == 0 {
                    queue.append(edge.targetNodeId)
                }
            }
        }

        if result.count != graph.nodes.count {
            throw CodeGenError.cycleDetected
        }
        return result
    }

    // MARK: - Node code generation (indicators)

    private func generateNodeCode(_ node: CanvasNode, graph: WorkflowGraph) -> String {
        let indent = "        "

        switch node.nodeType {
        case "indicator.rsi":
            let period = intParam(node, key: "period", default: 14)
            return indent + "dataframe['rsi'] = ta.RSI(dataframe, timeperiod=\(period))\n"

        case "indicator.macd":
            let fast = intParam(node, key: "fast", default: 12)
            let slow = intParam(node, key: "slow", default: 26)
            let signal = intParam(node, key: "signal", default: 9)
            return indent + "dataframe['macd'], dataframe['macdsignal'], dataframe['macdhist'] = ta.MACD(dataframe, fastperiod=\(fast), slowperiod=\(slow), signalperiod=\(signal))\n"

        case "indicator.bollinger":
            let period = intParam(node, key: "period", default: 20)
            let stdDev = doubleParam(node, key: "stdDev", default: 2.0)
            return indent + "bollinger = ta.BBANDS(dataframe, timeperiod=\(period), nbdevup=\(stdDev), nbdevdn=\(stdDev))\n" +
                   indent + "dataframe['bb_upper'] = bollinger['upperband']\n" +
                   indent + "dataframe['bb_middle'] = bollinger['middleband']\n" +
                   indent + "dataframe['bb_lower'] = bollinger['lowerband']\n"

        case "indicator.ma":
            let period = intParam(node, key: "period", default: 50)
            let maType = stringParam(node, key: "type", default: "EMA")
            switch maType {
            case "SMA":
                return indent + "dataframe['ma'] = ta.SMA(dataframe, timeperiod=\(period))\n"
            case "WMA":
                return indent + "dataframe['ma'] = ta.WMA(dataframe, timeperiod=\(period))\n"
            case "DEMA":
                return indent + "dataframe['ma'] = ta.DEMA(dataframe, timeperiod=\(period))\n"
            default:
                return indent + "dataframe['ma'] = ta.EMA(dataframe, timeperiod=\(period))\n"
            }

        case "indicator.atr":
            let period = intParam(node, key: "period", default: 14)
            return indent + "dataframe['atr'] = ta.ATR(dataframe, timeperiod=\(period))\n"

        case "indicator.stochastic":
            let kPeriod = intParam(node, key: "kPeriod", default: 14)
            let dPeriod = intParam(node, key: "dPeriod", default: 3)
            let smooth = intParam(node, key: "smooth", default: 3)
            return indent + "stoch = ta.STOCH(dataframe, fastk_period=\(kPeriod), slowk_period=\(smooth), slowd_period=\(dPeriod))\n" +
                   indent + "dataframe['stoch_k'] = stoch['slowk']\n" +
                   indent + "dataframe['stoch_d'] = stoch['slowd']\n"

        case "indicator.adx":
            let period = intParam(node, key: "period", default: 14)
            return indent + "dataframe['adx'] = ta.ADX(dataframe, timeperiod=\(period))\n" +
                   indent + "dataframe['plus_di'] = ta.PLUS_DI(dataframe, timeperiod=\(period))\n" +
                   indent + "dataframe['minus_di'] = ta.MINUS_DI(dataframe, timeperiod=\(period))\n"

        case "indicator.cci":
            let period = intParam(node, key: "period", default: 20)
            return indent + "dataframe['cci'] = ta.CCI(dataframe, timeperiod=\(period))\n"

        case "indicator.williamsR":
            let period = intParam(node, key: "period", default: 14)
            return indent + "dataframe['williams_r'] = ta.WILLR(dataframe, timeperiod=\(period))\n"

        case "indicator.mfi":
            let period = intParam(node, key: "period", default: 14)
            return indent + "dataframe['mfi'] = ta.MFI(dataframe, timeperiod=\(period))\n"

        case "indicator.obv":
            return indent + "dataframe['obv'] = ta.OBV(dataframe)\n"

        case "indicator.vwap":
            return indent + "dataframe['vwap'] = (dataframe['volume'] * (dataframe['high'] + dataframe['low'] + dataframe['close']) / 3).cumsum() / dataframe['volume'].cumsum()\n"

        case "filter.threshold":
            let threshold = doubleParam(node, key: "threshold", default: 70)
            let op = stringParam(node, key: "operator", default: ">")
            let pyOp = pythonOperator(op)
            let inputCol = resolveInputColumn(node, graph: graph, port: "value", fallback: "rsi")
            return indent + "dataframe['\(nodeColumnId(node.nodeType))_signal'] = (dataframe['\(inputCol)'] \(pyOp) \(threshold)).astype(int)\n"

        case "transform.smooth":
            let method = stringParam(node, key: "method", default: "MA")
            let inputCol = resolveInputColumn(node, graph: graph, port: "data", fallback: "close")
            switch method {
            case "指数":
                return indent + "dataframe['smoothed'] = dataframe['\(inputCol)'].ewm(span=10).mean()\n"
            default:
                return indent + "dataframe['smoothed'] = dataframe['\(inputCol)'].rolling(window=10).mean()\n"
            }

        case "math.expression":
            let expr = stringParam(node, key: "expression", default: "a + b")
            return indent + "# Math expression: \(expr)\n" + indent + "dataframe['math_result'] = dataframe['close']  # TODO: implement expression\n"

        default:
            let def = NodeRegistry.definition(for: node.nodeType)
            return indent + "# TODO: \(def?.name ?? node.nodeType)\n"
        }
    }

    // MARK: - Entry/Exit code generation

    private func generateEntryCode(_ node: CanvasNode, graph: WorkflowGraph) -> String {
        let indent = "        "
        var code = ""

        // Find upstream signal conditions
        let upstreamEdges = graph.edges.filter { $0.targetNodeId == node.id }
        let conditions = upstreamEdges.compactMap { edge -> String? in
            let sourceNode = graph.nodes.first { $0.id == edge.sourceNodeId }
            return sourceNode.map { "dataframe['\(nodeColumnId($0.nodeType))_signal'] == 1" }
        }

        let conditionStr = conditions.isEmpty ? "True" : conditions.joined(separator: " & ")

        code += indent + "dataframe.loc[\n"
        code += indent + "    \(conditionStr),\n"
        code += indent + "    'enter_long'] = 1\n"

        return code
    }

    private func generateExitCode(_ node: CanvasNode, graph: WorkflowGraph) -> String {
        let indent = "        "
        var code = ""

        let tp = doubleParam(node, key: "takeProfit", default: 5.0)
        let sl = doubleParam(node, key: "stopLoss", default: 2.0)

        code += indent + "# Take profit: \(tp)%, Stop loss: \(sl)%\n"
        code += indent + "dataframe.loc[\n"
        code += indent + "    (dataframe['close'] > dataframe['open'] * \(1 + tp / 100)),\n"
        code += indent + "    'exit_long'] = 1\n"

        return code
    }

    // MARK: - Template Registry

    private func resolveInputVariables(node: CanvasNode, graph: WorkflowGraph) -> [String: String] {
        var vars: [String: String] = [:]
        for edge in graph.edges where edge.targetNodeId == node.id {
            if let sourceNode = graph.nodes.first(where: { $0.id == edge.sourceNodeId }),
               let sourceDef = NodeRegistry.definition(for: sourceNode.nodeType) {
                let varName = sourceNode.config["outputVar"]?.value as? String
                    ?? "\(sourceNode.nodeType.replacingOccurrences(of: ".", with: "_"))_\(sourceNode.id.uuidString.prefix(8))"
                vars[edge.targetPortKey] = varName
            }
        }
        return vars
    }

    private var templateRegistry: [String: CodeTemplate] {
        [
            "indicator.rsi": CodeTemplate(
                indicatorCode: { node, vars in
                    let period = node.config["period"]?.value as? Double ?? 14
                    let source = vars["kline"] ?? "close"
                    let id = node.id.uuidString.prefix(8)
                    return "        dataframe['rsi_\(id)'] = ta.RSI(dataframe['\(source)'], timeperiod=\(Int(period)))"
                },
                entrySignalCode: { node, vars in
                    let id = node.id.uuidString.prefix(8)
                    let threshold = node.config["oversoldThreshold"]?.value as? Double ?? 30
                    return "                (dataframe['rsi_\(id)'] < \(Int(threshold)))"
                },
                exitSignalCode: { node, vars in
                    let id = node.id.uuidString.prefix(8)
                    let threshold = node.config["overboughtThreshold"]?.value as? Double ?? 70
                    return "                (dataframe['rsi_\(id)'] > \(Int(threshold)))"
                }
            ),
            "indicator.macd": CodeTemplate(
                indicatorCode: { node, vars in
                    let fast = node.config["fastPeriod"]?.value as? Double ?? 12
                    let slow = node.config["slowPeriod"]?.value as? Double ?? 26
                    let signal = node.config["signalPeriod"]?.value as? Double ?? 9
                    let source = vars["kline"] ?? "close"
                    let id = node.id.uuidString.prefix(8)
                    return """
                            macd_\(id) = ta.MACD(dataframe['\(source)'], fastperiod=\(Int(fast)), slowperiod=\(Int(slow)), signalperiod=\(Int(signal)))
                            dataframe['macd_\(id)'] = macd_\(id)['macd']
                            dataframe['macdsignal_\(id)'] = macd_\(id)['macdsignal']
                            dataframe['macdhist_\(id)'] = macd_\(id)['macdhist']
                    """
                },
                entrySignalCode: { node, vars in
                    let id = node.id.uuidString.prefix(8)
                    return "                (dataframe['macd_\(id)'] > dataframe['macdsignal_\(id)'])"
                },
                exitSignalCode: { node, vars in
                    let id = node.id.uuidString.prefix(8)
                    return "                (dataframe['macd_\(id)'] < dataframe['macdsignal_\(id)'])"
                }
            ),
        ]
    }

    // MARK: - Helpers

    private func intParam(_ node: CanvasNode, key: String, default defaultValue: Int) -> Int {
        if let val = node.widgetValues[key]?.value as? Int { return val }
        if let val = node.config[key]?.value as? Int { return val }
        if let val = node.widgetValues[key]?.value as? Double { return Int(val) }
        if let val = node.config[key]?.value as? Double { return Int(val) }
        return defaultValue
    }

    private func doubleParam(_ node: CanvasNode, key: String, default defaultValue: Double) -> Double {
        if let val = node.widgetValues[key]?.value as? Double { return val }
        if let val = node.config[key]?.value as? Double { return val }
        if let val = node.widgetValues[key]?.value as? Int { return Double(val) }
        if let val = node.config[key]?.value as? Int { return Double(val) }
        return defaultValue
    }

    private func stringParam(_ node: CanvasNode, key: String, default defaultValue: String) -> String {
        if let val = node.widgetValues[key]?.value as? String { return val }
        if let val = node.config[key]?.value as? String { return val }
        return defaultValue
    }

    private func resolveInputColumn(_ node: CanvasNode, graph: WorkflowGraph, port: String, fallback: String) -> String {
        guard let edge = graph.edges.first(where: { $0.targetNodeId == node.id && $0.targetPortKey == port }) else {
            return fallback
        }
        guard let sourceNode = graph.nodes.first(where: { $0.id == edge.sourceNodeId }) else {
            return fallback
        }
        let sourceDef = NodeRegistry.definition(for: sourceNode.nodeType)
        return sourceDef?.outputPorts.first?.name ?? fallback
    }

    private func nodeColumnId(_ nodeType: String) -> String {
        nodeType.replacingOccurrences(of: ".", with: "_")
    }

    private func pythonOperator(_ op: String) -> String {
        switch op {
        case ">":  return ">"
        case "<":  return "<"
        case "=":  return "=="
        case ">=": return ">="
        case "<=": return "<="
        default:   return ">"
        }
    }
}
