"""initial_schema

Revision ID: cafb0a7659e2
Revises: 
Create Date: 2026-06-04 19:59:52.952219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cafb0a7659e2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('last_heartbeat_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('ai_provider_configs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('api_key_encrypted', sa.String(), nullable=True),
    sa.Column('base_url', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ai_research_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('asset_type', sa.String(), nullable=False),
    sa.Column('analysis_date', sa.Date(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('runtime_config', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('rating', sa.String(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('final_decision', sa.Text(), nullable=True),
    sa.Column('market_report', sa.Text(), nullable=True),
    sa.Column('sentiment_report', sa.Text(), nullable=True),
    sa.Column('news_report', sa.Text(), nullable=True),
    sa.Column('fundamentals_report', sa.Text(), nullable=True),
    sa.Column('investment_debate', sa.JSON(), nullable=True),
    sa.Column('risk_debate', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_research_runs_symbol'), 'ai_research_runs', ['symbol'], unique=False)
    op.create_table('ai_usage_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('service', sa.String(), nullable=False),
    sa.Column('tokens_used', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attribution_reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trade_id', sa.Integer(), nullable=False),
    sa.Column('strategy_id', sa.Integer(), nullable=True),
    sa.Column('feature_contributions', sa.JSON(), nullable=True),
    sa.Column('top_loss_factors', sa.JSON(), nullable=True),
    sa.Column('market_context', sa.JSON(), nullable=True),
    sa.Column('summary', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('backtest_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('strategy_id', sa.Integer(), nullable=False),
    sa.Column('strategy_version_id', sa.String(), nullable=True),
    sa.Column('command_id', sa.String(), nullable=True),
    sa.Column('dsl_hash', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('start_date', sa.String(), nullable=False),
    sa.Column('end_date', sa.String(), nullable=False),
    sa.Column('initial_capital', sa.Float(), nullable=False),
    sa.Column('symbols', sa.JSON(), nullable=True),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('sharpe_ratio', sa.Float(), nullable=True),
    sa.Column('max_drawdown', sa.Float(), nullable=True),
    sa.Column('win_rate', sa.Float(), nullable=True),
    sa.Column('total_return', sa.Float(), nullable=True),
    sa.Column('profit_factor', sa.Float(), nullable=True),
    sa.Column('total_trades', sa.Integer(), nullable=True),
    sa.Column('data_source', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_backtest_runs_command_id'), 'backtest_runs', ['command_id'], unique=False)
    op.create_index(op.f('ix_backtest_runs_strategy_id'), 'backtest_runs', ['strategy_id'], unique=False)
    op.create_index(op.f('ix_backtest_runs_strategy_version_id'), 'backtest_runs', ['strategy_version_id'], unique=False)
    op.create_table('capital_pools',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('pool_type', sa.String(length=24), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('total_budget', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('max_position_pct_per_trade', sa.Numeric(precision=8, scale=6), nullable=False),
    sa.Column('max_total_exposure_pct', sa.Numeric(precision=8, scale=6), nullable=False),
    sa.Column('max_daily_loss_pct', sa.Numeric(precision=8, scale=6), nullable=False),
    sa.Column('max_drawdown_pct', sa.Numeric(precision=8, scale=6), nullable=False),
    sa.Column('allow_leverage', sa.Boolean(), server_default=sa.text('(false)'), nullable=False),
    sa.Column('allow_auto_trade', sa.Boolean(), server_default=sa.text('(false)'), nullable=False),
    sa.Column('requires_human_confirm', sa.Boolean(), server_default=sa.text('(true)'), nullable=False),
    sa.Column('emergency_stop', sa.Boolean(), server_default=sa.text('(false)'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('command_bus_commands',
    sa.Column('command_type', sa.String(length=64), nullable=False),
    sa.Column('aggregate_type', sa.String(length=64), nullable=False),
    sa.Column('aggregate_id', sa.UUID(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=24), server_default='pending', nullable=False),
    sa.Column('idempotency_key', sa.String(length=512), nullable=False),
    sa.Column('requested_by', sa.String(length=128), nullable=False),
    sa.Column('locked_by', sa.String(length=128), nullable=True),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('timeout_sec', sa.Integer(), nullable=False),
    sa.Column('cancel_requested', sa.Boolean(), server_default=sa.text('(false)'), nullable=False),
    sa.Column('correlation_id', sa.UUID(), nullable=True),
    sa.Column('causation_id', sa.UUID(), nullable=True),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index('idx_command_bus_lock', 'command_bus_commands', ['locked_by', 'locked_at'], unique=False, postgresql_where="status = 'running'")
    op.create_index('idx_command_bus_pending', 'command_bus_commands', ['status', 'priority', 'created_at'], unique=False, postgresql_where="status IN ('pending','retry_waiting')")
    op.create_table('correlation_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol_a', sa.String(), nullable=False),
    sa.Column('symbol_b', sa.String(), nullable=False),
    sa.Column('market', sa.String(), nullable=True),
    sa.Column('correlation', sa.Float(), nullable=False),
    sa.Column('window_days', sa.Integer(), nullable=True),
    sa.Column('alert_level', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dryrun_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('strategy_id', sa.Integer(), nullable=False),
    sa.Column('strategy_version_id', sa.String(), nullable=True),
    sa.Column('command_id', sa.String(), nullable=True),
    sa.Column('dsl_hash', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('pid', sa.Integer(), nullable=True),
    sa.Column('api_port', sa.Integer(), nullable=True),
    sa.Column('api_url', sa.String(), nullable=True),
    sa.Column('config_path', sa.String(), nullable=True),
    sa.Column('rules_path', sa.String(), nullable=True),
    sa.Column('symbols', sa.JSON(), nullable=True),
    sa.Column('stake_amount', sa.Float(), nullable=True),
    sa.Column('max_open_trades', sa.Integer(), nullable=True),
    sa.Column('initial_wallet', sa.Float(), nullable=True),
    sa.Column('exchange', sa.String(), nullable=True),
    sa.Column('total_trades', sa.Integer(), nullable=True),
    sa.Column('open_trades', sa.Integer(), nullable=True),
    sa.Column('total_profit', sa.Float(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('stopped_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dryrun_runs_command_id'), 'dryrun_runs', ['command_id'], unique=False)
    op.create_index(op.f('ix_dryrun_runs_strategy_id'), 'dryrun_runs', ['strategy_id'], unique=False)
    op.create_index(op.f('ix_dryrun_runs_strategy_version_id'), 'dryrun_runs', ['strategy_version_id'], unique=False)
    op.create_table('execution_ledger_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('source_system', sa.String(length=32), nullable=False),
    sa.Column('source_event_id', sa.String(length=256), nullable=True),
    sa.Column('event_hash', sa.String(length=128), nullable=False),
    sa.Column('strategy_run_id', sa.UUID(), nullable=True),
    sa.Column('freqtrade_run_id', sa.UUID(), nullable=True),
    sa.Column('command_id', sa.UUID(), nullable=True),
    sa.Column('trade_intent_id', sa.UUID(), nullable=True),
    sa.Column('risk_decision_id', sa.UUID(), nullable=True),
    sa.Column('symbol', sa.String(length=32), nullable=True),
    sa.Column('sequence_no', sa.BigInteger(), nullable=True),
    sa.Column('schema_version', sa.String(length=8), server_default='2.5', nullable=False),
    sa.Column('correlation_id', sa.UUID(), nullable=True),
    sa.Column('causation_id', sa.UUID(), nullable=True),
    sa.Column('raw_payload', sa.JSON(), nullable=True),
    sa.Column('normalized_payload', sa.JSON(), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', 'event_time'),
    sa.UniqueConstraint('event_hash', 'event_time', name='uq_ledger_event_hash')
    )
    op.create_index('idx_ledger_command', 'execution_ledger_events', ['command_id', 'event_time'], unique=False)
    op.create_index('idx_ledger_correlation', 'execution_ledger_events', ['correlation_id', 'event_time'], unique=False)
    op.create_index('idx_ledger_event_type', 'execution_ledger_events', ['event_type', 'event_time'], unique=False)
    op.create_index('idx_ledger_source_event', 'execution_ledger_events', ['source_system', 'source_event_id', 'event_type', 'event_time'], unique=True, sqlite_where=None)
    op.create_index('idx_ledger_strategy_run', 'execution_ledger_events', ['strategy_run_id', 'event_time'], unique=False)
    op.create_index('idx_ledger_symbol', 'execution_ledger_events', ['symbol', 'event_time'], unique=False)
    op.create_table('factor_research_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('market', sa.String(), nullable=True),
    sa.Column('universe', sa.JSON(), nullable=True),
    sa.Column('factor_name', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=True),
    sa.Column('qlib_config', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feature_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('snapshot_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', 'snapshot_at')
    )
    op.create_table('forecast_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('horizon', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('points', sa.JSON(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forecast_runs_symbol'), 'forecast_runs', ['symbol'], unique=False)
    op.create_table('freqai_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('strategy_id', sa.Integer(), nullable=True),
    sa.Column('model_name', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('training_config', sa.JSON(), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_freqai_runs_strategy_id'), 'freqai_runs', ['strategy_id'], unique=False)
    op.create_table('generated_strategy_artifacts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('risk_level', sa.String(), nullable=True),
    sa.Column('market', sa.String(), nullable=True),
    sa.Column('strategy_name', sa.String(), nullable=False),
    sa.Column('strategy_type', sa.String(), nullable=True),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('safety_status', sa.String(), nullable=True),
    sa.Column('safety_findings', sa.JSON(), nullable=True),
    sa.Column('backtest_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('knowledge_documents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('content_hash', sa.String(), nullable=False),
    sa.Column('content_type', sa.String(), nullable=False),
    sa.Column('chunk_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content_hash')
    )
    op.create_table('manipulation_scores',
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('timeframe', sa.String(length=8), nullable=False),
    sa.Column('scores', sa.JSON(), nullable=False),
    sa.Column('risk_level', sa.String(length=16), nullable=False),
    sa.Column('features', sa.JSON(), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('data_quality', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('is_read', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('outbox_events',
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('aggregate_type', sa.String(length=64), nullable=False),
    sa.Column('aggregate_id', sa.UUID(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='pending', nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('portfolio_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('portfolio_stress_tests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('market', sa.String(), nullable=True),
    sa.Column('scenario', sa.String(), nullable=False),
    sa.Column('portfolio_var_95', sa.Float(), nullable=False),
    sa.Column('portfolio_cvar', sa.Float(), nullable=False),
    sa.Column('max_potential_drawdown', sa.Float(), nullable=False),
    sa.Column('concentration_risk', sa.JSON(), nullable=True),
    sa.Column('recommendations', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('provider_traces',
    sa.Column('object_type', sa.String(length=32), nullable=False),
    sa.Column('object_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('model_version', sa.String(length=32), nullable=True),
    sa.Column('prompt_version', sa.String(length=32), nullable=True),
    sa.Column('task_type', sa.String(length=64), nullable=True),
    sa.Column('privacy_level', sa.String(length=16), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('estimated_cost_usd', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('input_hash', sa.String(length=128), nullable=True),
    sa.Column('output_hash', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_provider_traces_object', 'provider_traces', ['object_type', 'object_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_table('risk_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('strategy_id', sa.Integer(), nullable=True),
    sa.Column('market', sa.String(), nullable=True),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('action_taken', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('risk_policies',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('policy_type', sa.String(length=24), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='draft', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sentiment_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('market', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('raw_text', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('signal_identity',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('signals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_type', sa.String(length=64), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('source_name', sa.String(length=128), nullable=True),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('market', sa.String(length=16), server_default='crypto', nullable=False),
    sa.Column('timeframe', sa.String(length=8), nullable=True),
    sa.Column('direction', sa.String(length=16), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('score', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('risk_level', sa.String(length=16), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('permission', sa.JSON(), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', 'created_at')
    )
    op.create_index('idx_signals_symbol_status_created', 'signals', ['symbol', 'status', sa.literal_column('created_at DESC')], unique=False)
    op.create_table('slippage_attribution',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trade_id', sa.Integer(), nullable=False),
    sa.Column('signal_price', sa.Float(), nullable=False),
    sa.Column('filled_price', sa.Float(), nullable=False),
    sa.Column('execution_slippage', sa.Float(), nullable=False),
    sa.Column('spread_cost', sa.Float(), nullable=True),
    sa.Column('market_impact', sa.Float(), nullable=True),
    sa.Column('latency_cost', sa.Float(), nullable=True),
    sa.Column('slippage_pct', sa.Float(), nullable=False),
    sa.Column('diagnosis', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('strategies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('market', sa.String(), nullable=True),
    sa.Column('exchange', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('sharpe_ratio', sa.Float(), nullable=True),
    sa.Column('max_drawdown', sa.Float(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('strategies_v2',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('strategy_type', sa.String(length=64), nullable=False),
    sa.Column('source_type', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='draft', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('theme', sa.String(length=20), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('notifications_enabled', sa.Boolean(), nullable=True),
    sa.Column('default_exchange', sa.String(length=50), nullable=True),
    sa.Column('default_market', sa.String(length=50), nullable=True),
    sa.Column('risk_tolerance', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_settings_user_id'), 'user_settings', ['user_id'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('agent_signals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('message_type', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('market', sa.String(), nullable=False),
    sa.Column('direction', sa.String(), nullable=True),
    sa.Column('rating', sa.String(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('target_price', sa.Float(), nullable=True),
    sa.Column('stop_loss', sa.Float(), nullable=True),
    sa.Column('time_horizon', sa.String(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=True),
    sa.Column('linked_research_run_id', sa.Integer(), nullable=True),
    sa.Column('linked_strategy_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agent_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_signals_agent_id'), 'agent_signals', ['agent_id'], unique=False)
    op.create_index(op.f('ix_agent_signals_linked_research_run_id'), 'agent_signals', ['linked_research_run_id'], unique=False)
    op.create_index(op.f('ix_agent_signals_linked_strategy_id'), 'agent_signals', ['linked_strategy_id'], unique=False)
    op.create_index(op.f('ix_agent_signals_symbol'), 'agent_signals', ['symbol'], unique=False)
    op.create_table('ai_research_links',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('research_run_id', sa.Integer(), nullable=False),
    sa.Column('strategy_id', sa.Integer(), nullable=True),
    sa.Column('backtest_id', sa.Integer(), nullable=True),
    sa.Column('link_type', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['research_run_id'], ['ai_research_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_research_links_backtest_id'), 'ai_research_links', ['backtest_id'], unique=False)
    op.create_index(op.f('ix_ai_research_links_research_run_id'), 'ai_research_links', ['research_run_id'], unique=False)
    op.create_index(op.f('ix_ai_research_links_strategy_id'), 'ai_research_links', ['strategy_id'], unique=False)
    op.create_table('canvas_workflows',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('strategy_id', sa.Integer(), nullable=False),
    sa.Column('graph_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_canvas_workflows_strategy_id'), 'canvas_workflows', ['strategy_id'], unique=False)
    op.create_table('knowledge_chunks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('keywords', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['knowledge_documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_chunks_document_id'), 'knowledge_chunks', ['document_id'], unique=False)
    op.create_table('research_reports',
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=64), nullable=False),
    sa.Column('market', sa.String(length=16), server_default='crypto', nullable=False),
    sa.Column('timeframe', sa.String(length=8), server_default='1d', nullable=False),
    sa.Column('rating', sa.String(length=16), nullable=False),
    sa.Column('direction', sa.String(length=16), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('risk_level', sa.String(length=16), nullable=False),
    sa.Column('agent_opinions', sa.JSON(), server_default='{}', nullable=False),
    sa.Column('summary', sa.Text(), server_default='', nullable=False),
    sa.Column('evidence', sa.JSON(), server_default='[]', nullable=False),
    sa.Column('provider_trace_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['ai_research_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_research_reports_run', 'research_reports', ['run_id'], unique=False)
    op.create_index('idx_research_reports_symbol_created', 'research_reports', ['symbol', sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('ix_research_reports_symbol'), 'research_reports', ['symbol'], unique=False)
    op.create_table('risk_policy_versions',
    sa.Column('risk_policy_id', sa.UUID(), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('policy_json', sa.JSON(), nullable=False),
    sa.Column('policy_hash', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='draft', nullable=False),
    sa.Column('created_by', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['risk_policy_id'], ['risk_policies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('risk_policy_id', 'version_no')
    )
    op.create_table('signal_evidence',
    sa.Column('signal_id', sa.UUID(), nullable=False),
    sa.Column('evidence_type', sa.String(length=64), nullable=False),
    sa.Column('evidence_ref', sa.String(length=256), nullable=True),
    sa.Column('evidence_payload', sa.JSON(), nullable=True),
    sa.Column('source_uri', sa.String(length=512), nullable=True),
    sa.Column('quality_score', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['signal_id'], ['signal_identity.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('signal_lifecycle_events',
    sa.Column('signal_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('from_status', sa.String(length=16), nullable=True),
    sa.Column('to_status', sa.String(length=16), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('actor', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['signal_id'], ['signal_identity.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('signal_payloads',
    sa.Column('signal_id', sa.UUID(), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('structured_output', sa.JSON(), nullable=True),
    sa.Column('raw_output', sa.JSON(), nullable=True),
    sa.Column('trigger_condition', sa.JSON(), nullable=True),
    sa.Column('current_state', sa.JSON(), nullable=True),
    sa.Column('evidence_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['signal_id'], ['signal_identity.id'], ),
    sa.PrimaryKeyConstraint('signal_id')
    )
    op.create_table('signal_snapshots',
    sa.Column('signal_id', sa.UUID(), nullable=False),
    sa.Column('snapshot_reason', sa.String(length=64), nullable=False),
    sa.Column('snapshot_payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['signal_id'], ['signal_identity.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('strategy_versions',
    sa.Column('strategy_id', sa.UUID(), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=24), server_default='draft', nullable=False),
    sa.Column('dsl_version', sa.String(length=8), nullable=False),
    sa.Column('rule_dsl', sa.JSON(), nullable=False),
    sa.Column('dsl_hash', sa.String(length=128), nullable=False),
    sa.Column('created_by', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies_v2.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('strategy_id', 'version_no')
    )
    op.create_index('idx_strategy_versions_strategy', 'strategy_versions', ['strategy_id', sa.literal_column('version_no DESC')], unique=False)
    op.create_table('agent_signal_scores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('signal_id', sa.Integer(), nullable=False),
    sa.Column('verifiability_score', sa.Float(), nullable=False),
    sa.Column('evidence_score', sa.Float(), nullable=False),
    sa.Column('specificity_score', sa.Float(), nullable=False),
    sa.Column('novelty_score', sa.Float(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=False),
    sa.Column('scored_by', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['signal_id'], ['agent_signals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_signal_scores_signal_id'), 'agent_signal_scores', ['signal_id'], unique=False)
    op.create_table('signal_candidates',
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('symbol', sa.String(length=64), nullable=False),
    sa.Column('direction', sa.String(length=16), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('risk_level', sa.String(length=16), nullable=False),
    sa.Column('reasoning', sa.Text(), server_default='', nullable=False),
    sa.Column('entry_logic', sa.Text(), server_default='', nullable=False),
    sa.Column('exit_logic', sa.Text(), server_default='', nullable=False),
    sa.Column('suggested_indicators', sa.JSON(), server_default='[]', nullable=False),
    sa.Column('time_horizon', sa.String(length=16), server_default='1d', nullable=False),
    sa.Column('can_live_trade', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('can_backtest', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('can_paper_trade', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('requires_human_confirm', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['research_reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_signal_candidates_report', 'signal_candidates', ['report_id'], unique=False)
    op.create_index(op.f('ix_signal_candidates_symbol'), 'signal_candidates', ['symbol'], unique=False)
    op.create_table('strategy_risk_policy_bindings',
    sa.Column('strategy_version_id', sa.UUID(), nullable=False),
    sa.Column('risk_policy_version_id', sa.UUID(), nullable=False),
    sa.Column('capital_pool_id', sa.UUID(), nullable=False),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['capital_pool_id'], ['capital_pools.id'], ),
    sa.ForeignKeyConstraint(['risk_policy_version_id'], ['risk_policy_versions.id'], ),
    sa.ForeignKeyConstraint(['strategy_version_id'], ['strategy_versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('strategy_version_id', 'mode')
    )
    op.create_table('strategy_rule_dsl_versions',
    sa.Column('strategy_version_id', sa.UUID(), nullable=False),
    sa.Column('dsl_version', sa.String(length=8), nullable=False),
    sa.Column('rule_dsl', sa.JSON(), nullable=False),
    sa.Column('dsl_hash', sa.String(length=128), nullable=False),
    sa.Column('migration_from', sa.String(length=8), nullable=True),
    sa.Column('validation_result', sa.JSON(), nullable=True),
    sa.Column('validator_version', sa.String(length=8), server_default='2.5', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['strategy_version_id'], ['strategy_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('strategy_runs',
    sa.Column('strategy_version_id', sa.UUID(), nullable=False),
    sa.Column('capital_pool_id', sa.UUID(), nullable=True),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=32), server_default='created', nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stopped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['capital_pool_id'], ['capital_pools.id'], ),
    sa.ForeignKeyConstraint(['strategy_version_id'], ['strategy_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('execution_positions',
    sa.Column('latest_ledger_event_id', sa.UUID(), nullable=False),
    sa.Column('strategy_run_id', sa.UUID(), nullable=True),
    sa.Column('exchange', sa.String(length=32), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('position_side', sa.String(length=8), nullable=True),
    sa.Column('amount', sa.Numeric(precision=28, scale=12), nullable=True),
    sa.Column('entry_price', sa.Numeric(precision=28, scale=12), nullable=True),
    sa.Column('mark_price', sa.Numeric(precision=28, scale=12), nullable=True),
    sa.Column('unrealized_pnl', sa.Numeric(precision=28, scale=12), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('raw_payload', sa.JSON(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['strategy_run_id'], ['strategy_runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('strategy_run_id', 'exchange', 'symbol', 'position_side')
    )
    op.create_table('freqtrade_runs',
    sa.Column('strategy_run_id', sa.UUID(), nullable=False),
    sa.Column('container_id', sa.String(length=128), nullable=True),
    sa.Column('config_path', sa.String(length=512), nullable=False),
    sa.Column('rules_path', sa.String(length=512), nullable=False),
    sa.Column('rule_package_hash', sa.String(length=128), nullable=False),
    sa.Column('fixed_strategy_template', sa.String(length=128), server_default='PulseDeskUniversalStrategy.py', nullable=False),
    sa.Column('ft_db_url', sa.String(length=512), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('last_heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_reconciled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('api_base_url', sa.String(length=256), nullable=True),
    sa.Column('websocket_url', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['strategy_run_id'], ['strategy_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('growth_reports',
    sa.Column('strategy_run_id', sa.UUID(), nullable=True),
    sa.Column('strategy_version_id', sa.UUID(), nullable=True),
    sa.Column('report_type', sa.String(length=32), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=True),
    sa.Column('findings', sa.JSON(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['strategy_run_id'], ['strategy_runs.id'], ),
    sa.ForeignKeyConstraint(['strategy_version_id'], ['strategy_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('strategy_drafts',
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), server_default='', nullable=False),
    sa.Column('rule_dsl', sa.JSON(), nullable=False),
    sa.Column('dsl_valid', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('dsl_errors', sa.JSON(), server_default='[]', nullable=False),
    sa.Column('dsl_warnings', sa.JSON(), server_default='[]', nullable=False),
    sa.Column('source_type', sa.String(length=32), server_default='ai_research', nullable=False),
    sa.Column('auto_execute', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('requires_human_confirm', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('provider_trace_id', sa.UUID(), nullable=True),
    sa.Column('confirmed_strategy_id', sa.UUID(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['signal_candidates.id'], ),
    sa.ForeignKeyConstraint(['report_id'], ['research_reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_strategy_drafts_candidate', 'strategy_drafts', ['candidate_id'], unique=False)
    op.create_index('idx_strategy_drafts_report', 'strategy_drafts', ['report_id'], unique=False)
    op.create_table('trade_intents',
    sa.Column('intent_type', sa.String(length=32), nullable=False),
    sa.Column('strategy_run_id', sa.UUID(), nullable=False),
    sa.Column('strategy_version_id', sa.UUID(), nullable=False),
    sa.Column('feature_snapshot_id', sa.UUID(), nullable=True),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('side', sa.String(length=8), nullable=False),
    sa.Column('requested_position_pct', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='created', nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['strategy_run_id'], ['strategy_runs.id'], ),
    sa.ForeignKeyConstraint(['strategy_version_id'], ['strategy_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('execution_orders',
    sa.Column('latest_ledger_event_id', sa.UUID(), nullable=False),
    sa.Column('strategy_run_id', sa.UUID(), nullable=True),
    sa.Column('freqtrade_run_id', sa.UUID(), nullable=True),
    sa.Column('source_system', sa.String(length=32), nullable=False),
    sa.Column('source_order_id', sa.String(length=256), nullable=False),
    sa.Column('freqtrade_trade_id', sa.String(length=256), nullable=True),
    sa.Column('exchange', sa.String(length=32), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('side', sa.String(length=8), nullable=False),
    sa.Column('order_type', sa.String(length=16), nullable=True),
    sa.Column('price', sa.Numeric(precision=28, scale=12), nullable=True),
    sa.Column('amount', sa.Numeric(precision=28, scale=12), nullable=True),
    sa.Column('filled_amount', sa.Numeric(precision=28, scale=12), nullable=True),
    sa.Column('fee', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('raw_payload', sa.JSON(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['freqtrade_run_id'], ['freqtrade_runs.id'], ),
    sa.ForeignKeyConstraint(['strategy_run_id'], ['strategy_runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_system', 'source_order_id')
    )
    op.create_table('execution_trades',
    sa.Column('latest_ledger_event_id', sa.UUID(), nullable=False),
    sa.Column('strategy_run_id', sa.UUID(), nullable=True),
    sa.Column('freqtrade_run_id', sa.UUID(), nullable=True),
    sa.Column('source_system', sa.String(length=32), nullable=False),
    sa.Column('source_trade_id', sa.String(length=256), nullable=False),
    sa.Column('exchange', sa.String(length=32), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('side', sa.String(length=8), nullable=True),
    sa.Column('open_rate', sa.Numeric(precision=28, scale=12), nullable=True),
    sa.Column('close_rate', sa.Numeric(precision=28, scale=12), nullable=True),
    sa.Column('amount', sa.Numeric(precision=28, scale=12), nullable=True),
    sa.Column('profit_abs', sa.Numeric(precision=28, scale=12), nullable=True),
    sa.Column('profit_pct', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('raw_payload', sa.JSON(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['freqtrade_run_id'], ['freqtrade_runs.id'], ),
    sa.ForeignKeyConstraint(['strategy_run_id'], ['strategy_runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_system', 'source_trade_id')
    )
    op.create_table('risk_decisions',
    sa.Column('trade_intent_id', sa.UUID(), nullable=True),
    sa.Column('strategy_run_id', sa.UUID(), nullable=True),
    sa.Column('decision', sa.String(length=32), nullable=False),
    sa.Column('final_position_pct', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('risk_checks', sa.JSON(), nullable=False),
    sa.Column('risk_codes', sa.JSON(), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['strategy_run_id'], ['strategy_runs.id'], ),
    sa.ForeignKeyConstraint(['trade_intent_id'], ['trade_intents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('strategy_candidates',
    sa.Column('source_growth_report_id', sa.UUID(), nullable=False),
    sa.Column('source_strategy_version_id', sa.UUID(), nullable=False),
    sa.Column('candidate_dsl', sa.JSON(), nullable=False),
    sa.Column('candidate_dsl_hash', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=24), server_default='draft', nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('dsl_valid', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('dsl_errors', sa.JSON(), nullable=True),
    sa.Column('auto_execute', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['source_growth_report_id'], ['growth_reports.id'], ),
    sa.ForeignKeyConstraint(['source_strategy_version_id'], ['strategy_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trade_intent_signal_snapshots',
    sa.Column('trade_intent_id', sa.UUID(), nullable=False),
    sa.Column('signal_id', sa.UUID(), nullable=False),
    sa.Column('signal_status_at_trigger', sa.String(length=16), nullable=True),
    sa.Column('direction', sa.String(length=16), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('score', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('reasoning_snapshot', sa.Text(), nullable=True),
    sa.Column('evidence_snapshot', sa.JSON(), nullable=True),
    sa.Column('provider_trace_snapshot', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['signal_id'], ['signal_identity.id'], ),
    sa.ForeignKeyConstraint(['trade_intent_id'], ['trade_intents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_attributions',
    sa.Column('execution_order_id', sa.UUID(), nullable=False),
    sa.Column('strategy_version_id', sa.UUID(), nullable=False),
    sa.Column('rule_path', sa.String(length=256), nullable=True),
    sa.Column('attribution_confidence', sa.String(length=16), server_default='low', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['execution_order_id'], ['execution_orders.id'], ),
    sa.ForeignKeyConstraint(['strategy_version_id'], ['strategy_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_fills',
    sa.Column('execution_order_id', sa.UUID(), nullable=False),
    sa.Column('source_fill_id', sa.String(length=256), nullable=True),
    sa.Column('price', sa.Numeric(precision=28, scale=12), nullable=False),
    sa.Column('amount', sa.Numeric(precision=28, scale=12), nullable=False),
    sa.Column('fee', sa.JSON(), nullable=True),
    sa.Column('filled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('raw_payload', sa.JSON(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['execution_order_id'], ['execution_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_fills')
    op.drop_table('order_attributions')
    op.drop_table('trade_intent_signal_snapshots')
    op.drop_table('strategy_candidates')
    op.drop_table('risk_decisions')
    op.drop_table('execution_trades')
    op.drop_table('execution_orders')
    op.drop_table('trade_intents')
    op.drop_index('idx_strategy_drafts_report', table_name='strategy_drafts')
    op.drop_index('idx_strategy_drafts_candidate', table_name='strategy_drafts')
    op.drop_table('strategy_drafts')
    op.drop_table('growth_reports')
    op.drop_table('freqtrade_runs')
    op.drop_table('execution_positions')
    op.drop_table('strategy_runs')
    op.drop_table('strategy_rule_dsl_versions')
    op.drop_table('strategy_risk_policy_bindings')
    op.drop_index(op.f('ix_signal_candidates_symbol'), table_name='signal_candidates')
    op.drop_index('idx_signal_candidates_report', table_name='signal_candidates')
    op.drop_table('signal_candidates')
    op.drop_index(op.f('ix_agent_signal_scores_signal_id'), table_name='agent_signal_scores')
    op.drop_table('agent_signal_scores')
    op.drop_index('idx_strategy_versions_strategy', table_name='strategy_versions')
    op.drop_table('strategy_versions')
    op.drop_table('signal_snapshots')
    op.drop_table('signal_payloads')
    op.drop_table('signal_lifecycle_events')
    op.drop_table('signal_evidence')
    op.drop_table('risk_policy_versions')
    op.drop_index(op.f('ix_research_reports_symbol'), table_name='research_reports')
    op.drop_index('idx_research_reports_symbol_created', table_name='research_reports')
    op.drop_index('idx_research_reports_run', table_name='research_reports')
    op.drop_table('research_reports')
    op.drop_index(op.f('ix_knowledge_chunks_document_id'), table_name='knowledge_chunks')
    op.drop_table('knowledge_chunks')
    op.drop_index(op.f('ix_canvas_workflows_strategy_id'), table_name='canvas_workflows')
    op.drop_table('canvas_workflows')
    op.drop_index(op.f('ix_ai_research_links_strategy_id'), table_name='ai_research_links')
    op.drop_index(op.f('ix_ai_research_links_research_run_id'), table_name='ai_research_links')
    op.drop_index(op.f('ix_ai_research_links_backtest_id'), table_name='ai_research_links')
    op.drop_table('ai_research_links')
    op.drop_index(op.f('ix_agent_signals_symbol'), table_name='agent_signals')
    op.drop_index(op.f('ix_agent_signals_linked_strategy_id'), table_name='agent_signals')
    op.drop_index(op.f('ix_agent_signals_linked_research_run_id'), table_name='agent_signals')
    op.drop_index(op.f('ix_agent_signals_agent_id'), table_name='agent_signals')
    op.drop_table('agent_signals')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_user_settings_user_id'), table_name='user_settings')
    op.drop_table('user_settings')
    op.drop_table('strategies_v2')
    op.drop_table('strategies')
    op.drop_table('slippage_attribution')
    op.drop_index('idx_signals_symbol_status_created', table_name='signals')
    op.drop_table('signals')
    op.drop_table('signal_identity')
    op.drop_table('sentiment_data')
    op.drop_table('risk_policies')
    op.drop_table('risk_events')
    op.drop_index('idx_provider_traces_object', table_name='provider_traces')
    op.drop_table('provider_traces')
    op.drop_table('portfolio_stress_tests')
    op.drop_table('portfolio_snapshots')
    op.drop_table('outbox_events')
    op.drop_table('notifications')
    op.drop_table('manipulation_scores')
    op.drop_table('knowledge_documents')
    op.drop_table('generated_strategy_artifacts')
    op.drop_index(op.f('ix_freqai_runs_strategy_id'), table_name='freqai_runs')
    op.drop_table('freqai_runs')
    op.drop_index(op.f('ix_forecast_runs_symbol'), table_name='forecast_runs')
    op.drop_table('forecast_runs')
    op.drop_table('feature_snapshots')
    op.drop_table('factor_research_runs')
    op.drop_index('idx_ledger_symbol', table_name='execution_ledger_events')
    op.drop_index('idx_ledger_strategy_run', table_name='execution_ledger_events')
    op.drop_index('idx_ledger_source_event', table_name='execution_ledger_events', sqlite_where=None)
    op.drop_index('idx_ledger_event_type', table_name='execution_ledger_events')
    op.drop_index('idx_ledger_correlation', table_name='execution_ledger_events')
    op.drop_index('idx_ledger_command', table_name='execution_ledger_events')
    op.drop_table('execution_ledger_events')
    op.drop_index(op.f('ix_dryrun_runs_strategy_version_id'), table_name='dryrun_runs')
    op.drop_index(op.f('ix_dryrun_runs_strategy_id'), table_name='dryrun_runs')
    op.drop_index(op.f('ix_dryrun_runs_command_id'), table_name='dryrun_runs')
    op.drop_table('dryrun_runs')
    op.drop_table('correlation_snapshots')
    op.drop_index('idx_command_bus_pending', table_name='command_bus_commands', postgresql_where="status IN ('pending','retry_waiting')")
    op.drop_index('idx_command_bus_lock', table_name='command_bus_commands', postgresql_where="status = 'running'")
    op.drop_table('command_bus_commands')
    op.drop_table('capital_pools')
    op.drop_index(op.f('ix_backtest_runs_strategy_version_id'), table_name='backtest_runs')
    op.drop_index(op.f('ix_backtest_runs_strategy_id'), table_name='backtest_runs')
    op.drop_index(op.f('ix_backtest_runs_command_id'), table_name='backtest_runs')
    op.drop_table('backtest_runs')
    op.drop_table('attribution_reports')
    op.drop_table('ai_usage_logs')
    op.drop_index(op.f('ix_ai_research_runs_symbol'), table_name='ai_research_runs')
    op.drop_table('ai_research_runs')
    op.drop_table('ai_provider_configs')
    op.drop_table('agent_profiles')
    # ### end Alembic commands ###
